name: Overwrite some file

on:
  push:
    # branches:
    #   - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: src/MyApp/Version.cs
          write-mode: overwrite
          contents: |
            public static void Version {
                public static string GetVersion => "${{ steps.get-version.outputs.VERSION }}";
            }

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'
